### ISSUE TITLE
Change the look of the scrollbar

### ISSUE THREAD

**Issue by Zbergen-cli** [Zonnev/elementaryos5-firefox-theme#7]
Hello!

Can you change the scroll bar's appearance and behavior (hide, reduce size) in Firefox?

**Comment by Zonnev** [comment]
I tried to change the scrollbar some months ago and I found it was impossible without a javascript. I could reduce it's size and even hide it, but not make it round since it changes to square when you add CSS to the selectors. Basically, when using only CSS, we can only change the color and the width of the scrollbar.
https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color
https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width

**Comment by Zbergen-cli** [comment]
I'm sorry to hear that. Thank you very much for your answer)
